version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - 5601:5601
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    command: nginx -g 'daemon off;'
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  server:
    container_name: server
    image: aparedes/alpine-node-yarn
    environment:
      - API_KEY
    working_dir: /opt/server
    command: yarn start
    ports:
      - 9000:9000
    volumes:
      - ./server:/opt/server
  frontend:
    container_name: frontend
    image: aparedes/alpine-node-yarn
    working_dir: /opt/frontend
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/opt/frontend
