version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - 9200:9200
  nginx:
    container_name: nginx
    build: nginx
    depends_on:
      - frontend
      - server
    ports:
      - 80:80
  server:
    container_name: server
    build: server
    depends_on:
      - elasticsearch
    ports:
      - 9000:9000
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 3000:3000
